require "setup"
require "parse"
require "update"

require "TSerial"

app = {
    -- app state
    idle = true,
    paused = false,
    editing = false,
    error = false,
    viewingCode = false,
    viewingHeatmapForRule = 0, 
    focused = true,
    printing = false,

    -- on each input
    lastInputKey = nil,
    loopsSinceInput = 0,
    hitsSinceInput = 0,
    missesSinceInput = 0,

    -- update loop
    timeSinceLastUpdate = 0,
    updateInterval = 0.1, --0.05,

    -- settings. defaults before being rewritten by settings.lua
    settings = {
        pixelScale = 4,
        windowX = nil,
        windowY = nil,
        logRules = false,
    },
}

local mouseInput = {
    startX = 0,
    startY = 0,
    brushColor = 0,
}

local data = {
    -- loaded images and their associated tables
    -- tables are generated by parsing the images
    -- the board gets updated by the rules.
    board = {
        table = {}, -- the current state
        imagedata = nil,
        imageHash = 0,
        width = 0,
        height = 0,
    },
    rules = {
        table = {}, -- the rules
        imagedata = nil,
        imageHash = 0,
        width = 0,
        height = 0,
    },
    symbols = {
        table = {}, -- the special symbols
        imagedata = nil,
        imageHash = 0,
        width = 0,
        height = 0,
    },
    output = {
        -- output image
        -- no table or hash, as it's generated from the board or rules
        image = nil, -- the actual image being drawn
        imagedata = nil,
        width = 0,
        height = 0,
    },
}

function love.load() 
    loadSettings(app.settings, "settings.lua")
    loadImages(data)
end

function restartLoop()
    if app.loopsSinceInput > 0 then
        app.loopsSinceInput = 0
        print("restarted loop and heatmap.")
    end
end

function love.update(dt)

    -- update every <updateInterval> seconds
    local updateNow = false
    app.timeSinceLastUpdate = app.timeSinceLastUpdate + dt
    if app.timeSinceLastUpdate > app.updateInterval then
        app.timeSinceLastUpdate = app.timeSinceLastUpdate - app.updateInterval
        updateNow = true
    end

    if updateNow then updateTitle(data) end

    if not app.focused and love.window.hasFocus() then
        -- resume when window regains focus
        app.focused = true
        print("regained focus.")   
        loadImages(data)

    elseif app.focused and not love.window.hasFocus() then
        app.focused = false
        print("lost focus.")         
        -- window position
        app.settings.windowX, app.settings.windowY = love.window.getPosition()
        return
    end

    if app.error or app.viewingCode or app.idle or app.paused then
        return
    end

    -- state is shown and unpaused and not idle (more potential changes to be made)
    if updateNow then
        -- new state, apply rules once
        local madeChanges, hits, misses = updateBoard(data.board.table, data.rules.table)
        app.loopsSinceInput = app.loopsSinceInput + 1
        app.hitsSinceInput = app.hitsSinceInput + hits
        app.missesSinceInput = app.missesSinceInput + misses
        -- print("turn " .. app.loopsSinceInput .. ".")
        if not madeChanges then
            app.idle = true
            print("   idle after " .. app.loopsSinceInput .. " turns.")
            print("   total: " .. app.hitsSinceInput .. "/" .. app.missesSinceInput + app.hitsSinceInput .. " matches.")
            print("   hit rate is " ..  string.format("%.3f", (app.hitsSinceInput / (app.missesSinceInput + app.hitsSinceInput)) * 100)  .. "%.")
            print()
            app.hitsSinceInput, app.missesSinceInput = 0, 0
            -- no return here, so the image is still updated once more.
            -- this can be used for (resetting) visual effects.
        end
        -- update image
        updateImagedata(data.output.imagedata, data.board.table)
        data.output.image:replacePixels(data.output.imagedata)
    end
end

function love.draw()
    if app.error then return end

    -- draw output image using the scale. matches window size.
    love.graphics.scale(app.settings.pixelScale, app.settings.pixelScale)
    love.graphics.draw(data.output.image, 0, 0)
    love.graphics.reset()

    --love.graphics.setColor(1, 0, 0)
    --love.graphics.print("FPS: "..tostring(love.timer.getFPS( )), 0, 0)
    
    love.graphics.setColor(1, 1, 1)
end

function love.quit()
    -- window position
    app.settings.windowX, app.settings.windowY = love.window.getPosition()

    -- save settings on quit
    local contents = TSerial.pack(app.settings, false, true)
    love.filesystem.write("settings.lua", contents)
end

-- input handling

function love.keypressed(key, scancode, isrepeat) 
    if key == "escape" then
        -- quit
        love.event.quit()

    elseif key == "space" and not app.viewingCode then
        -- pause
        app.paused = not app.paused
        print(app.paused and "paused." or "unpaused.")

        -- get out of special views
        app.viewingHeatmapForRule = 0
       
        -- output one more time, to show if paused or not
        updateImagedata(data.output.imagedata, data.board.table)
        data.output.image:replacePixels(data.output.imagedata)

    elseif key == "r" and not app.viewingCode then
        -- reset
        print("resetting state.")
        updatePallette()
        app.timeSinceLastUpdate = 0
        -- window position
        app.settings.windowX, app.settings.windowY = love.window.getPosition()
        setupWindow(data.board.width, data.board.height, app.settings)
        setupOutput(data) 
    
    elseif key == "l" then
        -- reload symbols, board and rules
        loadImages(data)
    
    elseif key == "s" then
        -- save image
        if app.viewingCode then
            print("cannot save image while viewing code.")
            return
        end
        print("saving image")

        app.printing = true
        updateImagedata(data.output.imagedata, data.board.table)

        local fileData = data.output.imagedata:encode("png", "output.png")
        love.filesystem.write("output.png", fileData)
        print("image saved as output.png in path: " .. love.filesystem.getSaveDirectory())

        app.printing = false
        updateImagedata(data.output.imagedata, data.board.table)
    
    elseif key == "tab" then
        -- switch between rule and board display
        local toX, toY
        if app.viewingCode then
            app.viewingCode = false
            print("viewing board.")
            toX, toY = data.board.width, data.board.height
        else
            app.viewingCode = true
            print("viewing rules.")
            toX, toY = data.rules.width, data.rules.height
        end
        setupWindow(toX, toY, app.settings)
        setupOutput(data)

    elseif key == "up" or key == "down" or key == "left" or key == "right" then
        -- input keys for games, etc.
        if app.viewingCode then
            return
        end

        app.lastInputKey = key -- for this next update, access the last key pressed. reset in the update fn
        print("input key: " .. key)

        restartLoop()
        app.timeSinceLastUpdate = 0
        app.idle = false

    elseif key == "1" or key == "2" then
        -- show different heatmaps over the state that represent where each rule matched since last input
        app.viewingHeatmapForRule = app.viewingHeatmapForRule + (key == "1" and -1 or 1)

        -- cycle through rules
        if app.viewingHeatmapForRule < -1 then
            app.viewingHeatmapForRule = #data.rules.table
        elseif app.viewingHeatmapForRule > #data.rules.table then
            app.viewingHeatmapForRule = -1
        end

        -- 0 is the default state without heatmap
        if app.viewingHeatmapForRule == 0 then
            print("viewing state without heatmap.")
        else
            if app.viewingHeatmapForRule == -1 then
                print("viewing per-cycle heatmap for all rules.")
            else
                print("viewing heatmap for rule: " .. app.viewingHeatmapForRule)
                -- wip. what order are those heatmaps in? is the displayed rule the same?
                -- get the rule
                local rule = data.rules.table[app.viewingHeatmapForRule]
                ---- print to console
                for i, v in ipairs(rule.rewrites) do
                    local combinedTable = deepCopy(v.right)
                    table.insert(combinedTable, 1, v.left)
                    printPatternsSideBySide(combinedTable)
                end
            end
        end
        updateImagedata(data.output.imagedata, data.board.table)
        data.output.image:replacePixels(data.output.imagedata)
    else
        --print("key pressed: " .. key)
    end
end

-- scroll
function love.wheelmoved(x, y)

    -- first get position of window
    app.settings.windowX, app.settings.windowY = love.window.getPosition()

    if y > 0 then
        -- scroll up
        app.settings.pixelScale = app.settings.pixelScale + 1
    elseif y < 0 then
        -- scroll down
        app.settings.pixelScale = math.max(1, app.settings.pixelScale - 1)
    end
    local baseWidth, baseHeight = data.output.imagedata:getWidth(), data.output.imagedata:getHeight()
    setupWindow(baseWidth, baseHeight, app.settings)
end

function love.mousepressed(x, y, button, istouch, presses)
    mouseInput.brushColor = button == 1 and 0 or 1
    if button == 1 or button == 2 then
        app.editing = true
        local x, y = mouseToCoordinate(x, y)
        mouseInput.startX, mouseInput.startY = x, y

        if app.viewingCode then
            return
        end
        local previewBoard = deepCopy(data.board.table)
        drawInGrid(previewBoard, x, y, mouseInput)
    end
end

function love.mousemoved(x, y, dx, dy, istouch)
    if love.mouse.isDown(1) or love.mouse.isDown(2) then
        local x, y = mouseToCoordinate(x, y)

        if app.viewingCode then
            return
        end
        local previewBoard = deepCopy(data.board.table)
        drawInGrid(previewBoard, x, y, mouseInput)
    end
end

function love.mousereleased(x, y, button, istouch, presses)
    if button == 1 or button == 2 then
        app.editing = false
        app.idle = false
        local x, y = mouseToCoordinate(x, y)

        if app.viewingCode then
            return
        end
        drawInGrid(data.board.table, x, y, mouseInput)
    end
    mouseInput.startX, mouseInput.startY = 0, 0
end

function mouseToCoordinate(x, y)
    x, y = math.floor(x / app.settings.pixelScale) + 1, math.floor(y / app.settings.pixelScale) + 1
    -- clamp to image size
    x = math.max(1, math.min(x, data.output.imagedata:getWidth()))
    y = math.max(1, math.min(y, data.output.imagedata:getHeight()))
    return x, y
end

function drawInGrid(grid, endX, endY, mouseInput)
    local startX, startY = mouseInput.startX, mouseInput.startY
    if startX == x and startY == y then 
        grid[y][x] = mouseInput.brushColor
    else 
        for i = math.min(startY, endY), math.max(startY, endY) do
            for j = math.min(startX, endX), math.max(startX, endX) do
                if i > 0 and j > 0 then grid[i][j] = mouseInput.brushColor end
            end
        end
    end
    restartLoop()
    updateImagedata(data.output.imagedata, grid)
    data.output.image:replacePixels(data.output.imagedata)
end


-- helper functions

function printPatternsSideBySide(tables)
    print()
    local tallestSize = 0
    for _, symbol in ipairs(tables) do
        if type(symbol) ~= "string" then
            tallestSize = math.max(tallestSize, #symbol)
        end
    end

    for y = 1, tallestSize do -- for each row, print row of the symbols side by side
        io.write("   ")
        for _, symbol in ipairs(tables) do -- each symbol
            if type(symbol) == "string" then
                -- keyword
                if y == 1 then
                    io.write(symbol)
                else
                    -- match the width of the word with spaces underneath
                    for _ = 1, #symbol do
                        io.write(" ")
                    end
                end
            else 
                -- 2d table
                if type(symbol[1]) ~= "table" then
                    print("not a 2d table")
                    return
                end
                if y <= #symbol then
                    for x = 1, #symbol[y] do
                        local char = symbol[y][x] == 1 and "$$" or symbol[y][x] == 0 and "[]" or ". "
                        io.write(char)
                    end
                else
                    for _ = 1, #symbol[1] do
                        io.write("  ")
                    end
                end
            end
            io.write("  ") -- space between symbols
        end
        print()
    end
end

function swapAxes(t)
    local newTable = {}
    for y = 1, #t[1] do
        newTable[y] = {}
        for x = 1, #t do
            newTable[y][x] = t[x][y]
        end
    end
    return newTable
end

function deepCopy(table)
    local newTable = {}
    for i, part in ipairs(table) do
        if type(part) == "table" then
            newTable[i] = deepCopy(part)
        else
            newTable[i] = part
        end
    end
    return newTable
end

function shallowCopy(table)
    local newTable = {}
    for i, part in ipairs(table) do
        newTable[i] = part
    end
    return newTable
end

function shiftPattern(table, dx, dy)
    local width = #table[1]
    local height = #table
    local newTable = {}
    for y = 1, height do
        newTable[y] = {}
        for x = 1, width do
            newTable[y][x] = table[(y + dy - 1) % height + 1][(x + dx - 1) % width + 1]
        end
    end
    return newTable
end

function flipPattern(table, flipHorizontal)
    local width = #table[1]
    local height = #table
    local newTable = {}
    for y = 1, height do
        newTable[y] = {}
        for x = 1, width do
            newTable[y][x] = table[flipHorizontal and y or height - y + 1][flipHorizontal and width - x + 1 or x]
        end
    end
    return newTable
end

function rotatePattern(table)
    local width = #table[1]
    local height = #table
    local newTable = {}
    for x = 1, width do
        newTable[x] = {}
        for y = 1, height do
            newTable[x][y] = table[height - y + 1][x]
        end
    end
    if patternsEqual(table, newTable) then
        return nil
    end
    return newTable
end

function patternsEqual(matrix1, matrix2)
    if #matrix1 ~= #matrix2 or #matrix1[1] ~= #matrix2[1] then
        return false -- different dimensions, so not equal
    end
    local rows, cols = #matrix1, #matrix1[1]
    for i = 1, rows do
        for j = 1, cols do
            if matrix1[i][j] ~= matrix2[i][j] then
                return false
            end
        end
    end
    return true
end

function imageHash(imageData)
    local hash = 0
    local width, height = imageData:getDimensions()

    for y = 0, height - 1 do
        for x = 0, width - 1 do
            local r, g, b, a = imageData:getPixel(x, y)
            hash = hash + (r * 31 + g * 37 + b * 41 + a * 43)
        end
    end
    return hash
end
